### ISSUE TITLE
Just want to say hi

### ISSUE THREAD

**Issue by GrimPixel** [cutthroat78/Language-Learning-Resources#1]
There is already a list of resources:
https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/Internet-resources-for-polyglots

Would you like to work together?

**Comment by cutthroat78** [comment]
Thanks very much for sharing this with me, however one of the points of this repo is to have lists of resources specific to a language. I mostly center around learning Native American languages and other endangered languages from English. Another reason I made this repo is to list all of the resources I might or will use in making my own learning resources to help others learn these languages. I have made it a GitHub repo and GitHub pages instance because I think that makes it easy to use and contribute to if anybody has any suggestions, requests or ideas. 

At some point, I may add the "way I would learn this language guide" to each page with the mine and other resources I recommend using and tips and tricks and other stuff

You can see a sheet of my progress with making my own resources [here](https://gist.github.com/cutthroat78/d543e524a021636dc5afd035365237cc)

I (will) make: 
Anki decks to help teach vocab
A [LibreLingo Course](https://github.com/LibreLingo/LibreLingo) to teach grammar and some vocab in a Duolingo like way
A Dictionary (if it is needed) to help teach and track vocab in my other resources
A word games and wordle for that language to help learn vocab and practise words people may have learned from the anki deck

I will include links to your page and the other child page in my repo and language pages, when I get a chance. If you have anything to suggest putting in or doing you can make a pull request or create an issue and you are free to use/link any resources in this repo on your page 

I would like to work together. However I will still be working on this repo for my own personal use

**Comment by GrimPixel** [comment]
Thank you for your reply! Thank you for including that page!

Yes, we all have our own focuses. If you want to copy some links there, then no problem, because a list is not creative work and thus doesn't involve copyright.

Several titles of “Internet resources for polyglots” are child pages as well, the most complete ones being Dictionary and Course. It's not necessary to put them on your README again, since they are on “Internet resources for polyglots” already. There are other pages on Polyglot Club Wiki, where you can find out what kind of person I am. We have some interests in common: language learning and Arch Linux.

I see, you are spending time on Native American languages. I know a website, and it's the only one I know about them: http://www.native-languages.org/.
I would like to ask if you know these people, because I am working on a program that turns number from symbol to writing, so I think I may find help.

Let me comment on your plans:
As for Anki decks, I would prefer creating TSV files and importing them. I have a page on it https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/How-to-make-a-TSV-file. Words can be taken from resources on that Dictionary page. There is a page of Anki decks and once the deck is finished and get shared, they can be put on the list https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/Helpful-Anki-Shared-Decks
As for LibreLingo courses, I have seen criticism around Duolingo and according to my own experience, its focus is on practice and requires too much work to create all possible correct answers. I would prefer to have cloze only if it's me who create them.
As for the dictionary to help to teach and track, I guess frequency lists are what you need.
As for word games, some are already included in “Internet resources for polyglots”. I am also trying to figure out how to customize them, but I have no experience on those programming languages. It will take some time to complete.

If you like, you can also create other teaching materials in mind map, hierarchical notebook or other forms.

**Comment by cutthroat78** [comment]
I will check your page for resources as you can check mine for resources too!

I don't know the people at http://www.native-languages.org/, but I immensely grateful for the website as it helped me so much with finding new resources and giving me info about certain languages
Their contact page is [here](http://www.native-languages.org/faq.htm), if you need it

My anki decks will be done on csv and all of the materials used to make them will be available in repo along with the .apkg version of the deck for easy import. You can see a template of how I do that [here](https://github.com/cutthroat78/Template-Language-Anki-Deck). I also like keeping the csv as I or others can easily use websites like [this](https://tableconvert.com/csv-to-markdown) to change the data type to use for other purposes.
I will link my anki on this page, when I feel that they are sufficient enough for people to use
https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/Helpful-Anki-Shared-Decks

In my opinion, Duolingo works for me, it may not work for everyone but I and others I know enjoy using it. LibreLingo has a feature where markdown files can been shown before doing or practising a skill. My plan for the course is for the markdown file to show an explanation of a grammar rule and then you can practise that grammar rule with the exercises in the skill.

I only create dictionaries if there isn't a good enough one available and I am using other resources to make wordlists manually. Frequency lists would not be available for the small languages I am and want to work with and by tracking I meant keep track of which words I have used in a resource and which I haven't used

By "word games", I was specifically talking about a program [Szabgab](https://github.com/szabgab/) had made. [Word games](https://github.com/szabgab/word-games-code) uses a json file ([example json file](https://github.com/szabgab/word-games-english/blob/main/categories.json)) to hold data of words and their categories. Word games is planned to have games for people proficient in a language and language learners

**Comment by GrimPixel** [comment]
Glad to see that I helped you. I could find out how to contact them. I just don't want to do it before I am ready to add their languages.

I am looking forward to seeing your decks.
There is a tool to convert data: [PyGlossary](https://github.com/ilius/pyglossary)
There is a list of individual tools doing so: [Structured text tools](https://github.com/dbohdan/structured-text-tools)
You can check out that add-on recommendation page as well, since it may help.

I saw LibreLingo. They didn't show that feature in their demo lesson. That's a pity. 
I use ghostwriter https://wereturtle.github.io/ghostwriter/ to write Markdown. I feel great with it. You may try it out.
There are other courses than Duolingo. Some of them put Duolingo to shame. Seeing them, I have realized how courses can be. For Japanese, there are a grammar and a practice sites
[Imabi](https://www.imabi.net/)
[Elon.io](https://elon.io/learn-japanese/lessons)
Your lessons would be better than those on Duolingo, I think, since you are on your own, instead of having too many cooks.

You are creating word lists. That is good. Library G will help, if you don't mind.

That word game is hangman with a category, and the category makes it too easy, like for kindergarten kids. Hangman is very easy to write, [GeeksforGeeks](https://www.geeksforgeeks.org/hangman-game-python/) has it with CLI, [CodesSpeedy](https://www.codespeedy.com/hangman-game-with-gui-in-python-using-tkinter/) has it with GUI. If I were you, I would like to modify the code to let it recognize plain text, in order not to type so many quotation marks.

**Comment by cutthroat78** [comment]
Word games will have more games down the road. It is still a work in progress. It is also ran easily with github pages and is on a website that is easily accessible for non-techy language learners

Ghostwriter is cool but I use vim for everything and I use a command tool called [glow](https://github.com/charmbracelet/glow) to render markdown files in the CLI

I think for JSON quotation marks are needed to recognise strings

Thanks for the data conversion tools, as I always just googled for a website to do it but getting CLI tools to do the same things help with my mostly CLI workflow

Two things I have to say about Duolingo is that even if it is not good for learning, it helps people go over the edge of not learning a language to starting and then people may move to more and better resources and Duolingo is also very good at keeping people consistent on learning and in my experience and opinion, no matter how effective your study/learning method is, consistency is more important (but that is just my opinion)

**Comment by GrimPixel** [comment]
I am not paying much attention to word games. They can be useful if they allow people to use their own lists at ease.

I would simply use newline character to separate strings. If I have to use a tree-structure, I prefer YAML.

Duolingo looks gaudy with those clip arts and sounds for me. Duolingo caters to current people's mind: succeed as fast as possible. It skips the necessary steps to understand everything about the language and just let learners imitate. It gives learners a sense of having learned something by the visual and auditory effects, and those achievements, which serious learners don't care about. In US-American style of education, it's all about encouragement. For Duolingo, it also carries a commercial benefit: attract customers.
Here comes the difference between our ideas: you think it is more important to attract people, I think it is more important to put the focus on quality.

**Comment by GrimPixel** [comment]
You can take a look at the wiki now. Vincent is creating some Cherokee lessons. Other people can see them and contribute to them as well. Want to have a try?

**Comment by cutthroat78** [comment]
Forgot to reply this. I am currently moving everything over to my digital garden as it is a format and system that suits me better.

I don't care about attracting more people, what I think is best in a language learning platform is a platform that makes it easy to start learning a language and keeps you motivated. Dedicated language learns like myself don't care or need that as we motivate ourselves, but to get normal people who don't have time to put into researching and finding the best way to do it, but still want to learn a language and integrate into their everyday life and routine. I still stick with my belief that the method of learning isn't as important as your consistency of doing said method. If you hate doing the (most) efficient method to learn a language, then you are going to end up not doing it. Finding a method and system that suits the way you like learning is something you are going to stick with and make progress in, even if it isn't very efficient.

Duolingo is a perfect platform and I disagree with a lot about it and you are right that they care more about bringing in users as this brings profit and they are profit driven, but I still feel that we can learn from what they do well that works well for users and helps them learn better and implement such a thing in things like LibreLingo, LibreLingo courses, Anki, Anki decks, Anki extensions, etc.

When I get around to it I will be making a "general resources" page on my digital garden for resources that I will use to start investigating a language/topic and will put polyglotclub.com in it, when I get around to doing that and if polyglotclub.com has (sub)pages or anything on a particular language, I will include that in the page for that language.

I am going to close this issue as I will be moving stuff from this repo to other repos and my digital garden and then archiving this repo

- [My Digital Garden](https://sionnach.xyz)
- [Digital Garden Repo](https://github.com/cutthroat78/digital-garden)
